'use client'

import { useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { MessageCircle, Send, X, RotateCcw } from 'lucide-react'

const greeting = "Welcome to VRLS. Tell me a little about the transformation challenge you're working through."
const prompts = ['Our Agile transformation has stalled', "We're restructuring our operating model", 'We need help managing organizational change', "Our teams are Agile but delivery isn't improving", 'We want to move from projects to products']

export default function VRLSConcierge() {
  const [open, setOpen] = useState(false); const [messages, setMessages] = useState([{ role: 'assistant', content: greeting }]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const session = useRef(null)
  const reset = () => { session.current = null; setMessages([{ role: 'assistant', content: greeting }]); setInput('') }
  const send = async (value = input) => {
    const message = value.trim(); if (!message || loading) return; setInput(''); setMessages(m => [...m, { role: 'user', content: message }]); setLoading(true)
    try { const res = await fetch('/api/concierge', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: session.current, message }) }); const data = await res.json(); session.current = data.sessionId || session.current; setMessages(m => [...m, { role: 'assistant', content: data.reply || 'I could not respond just now. Please try again.' }]) }
    catch { setMessages(m => [...m, { role: 'assistant', content: 'I could not connect just now. Please try again, or start a conversation with our team.' }]) } finally { setLoading(false) }
  }
  return <><button onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-[70] inline-flex items-center gap-2 rounded-full border border-white/15 bg-graphite-800 px-4 py-3 text-sm text-foreground shadow-2xl hover:border-electric" aria-label="Ask VRLS"><MessageCircle className="h-4 w-4 text-gold" /> Ask VRLS</button><AnimatePresence>{open && <motion.aside initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 30 }} className="fixed inset-y-0 right-0 z-[80] flex w-full max-w-md flex-col border-l border-border bg-graphite-900 p-5 shadow-2xl" role="dialog" aria-modal="true" aria-label="VRLS Concierge"><div className="flex items-start justify-between border-b border-border pb-5"><div><h2 className="font-display text-xl font-semibold">VRLS Concierge</h2><p className="mt-1 text-sm text-muted-foreground">Explore your transformation challenge.</p></div><div className="flex gap-2"><button onClick={reset} className="p-2 text-muted-foreground hover:text-foreground" aria-label="Reset conversation"><RotateCcw className="h-4 w-4" /></button><button onClick={() => setOpen(false)} className="p-2 text-muted-foreground hover:text-foreground" aria-label="Close concierge"><X className="h-5 w-5" /></button></div></div><div className="flex-1 space-y-3 overflow-y-auto py-5">{messages.map((m, i) => <div key={i} className={m.role === 'user' ? 'ml-10 rounded-2xl rounded-br-sm bg-electric px-4 py-3 text-sm' : 'mr-8 rounded-2xl rounded-bl-sm bg-white/[0.05] px-4 py-3 text-sm leading-relaxed'}>{m.content}</div>)}{loading && <div className="text-sm text-muted-foreground">Thinking…</div>}{messages.length === 1 && <div className="flex flex-wrap gap-2">{prompts.map(p => <button key={p} onClick={() => send(p)} className="rounded-full border border-border px-3 py-2 text-left text-xs text-muted-foreground hover:border-electric hover:text-foreground">{p}</button>)}</div>}</div><div className="flex gap-2 border-t border-border pt-4"><input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') send() }} className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none" placeholder="Tell us what's changing…" /><button onClick={() => send()} disabled={loading || !input.trim()} className="btn-gold rounded-xl p-3 disabled:opacity-40" aria-label="Send message"><Send className="h-4 w-4" /></button></div></motion.aside>}</AnimatePresence></>
}
