// All copy + data lives here so real content can be swapped later
// WITHOUT touching layouts or interactions. (No em dashes anywhere.)

export const content = {
  brand: {
    name: 'VIRELLIS',
    tagline: 'Transforming Strategy into Delivery.',
    altTagline: 'Where Enterprise Transformation Meets Intelligent Delivery.',
  },
  nav: [
    { label: 'The Studio', href: '#studio' },
    { label: 'Framework', href: '#framework' },
    { label: 'Command Center', href: '#dashboard' },
    { label: 'Founder', href: '#founder' },
    { label: 'Leadership', href: '#leadership' },
    { label: 'Concierge', href: '#concierge' },
  ],
  hero: {
    eyebrow: 'ENTERPRISE TRANSFORMATION HEADQUARTERS',
    title: 'The operating system for enterprise transformation.',
    subtitle:
      'Virellis partners with government, healthcare, financial services, and technology enterprises to turn strategic ambition into governed, measurable delivery.',
    cta: 'Explore the Studio',
    cta2: 'Enter the Command Center',
    scrollHint: 'Scroll to disassemble the system',
  },
  studio: {
    eyebrow: 'THE TRANSFORMATION STUDIO',
    title: 'Eight domains. One delivery philosophy.',
    subtitle:
      'Virellis is structured as a single operating model. Eight integrated disciplines, one delivery philosophy, one senior consultant who knows the whole picture. Not a firm that scales headcount. A headquarters that scales thinking.',
  },
  framework: {
    eyebrow: 'THE ENTERPRISE DELIVERY FRAMEWORK',
    title: 'One operating model. Nine disciplined stages.',
    subtitle: 'Every Virellis engagement moves through the same governed lifecycle, from strategic intent to proven benefits. Select a stage to see how it is delivered.',
    stages: [
      { name: 'Strategy', summary: 'Align ambition, value and fundability so the programme starts with a mandate the board owns.', deliverables: ['Vision & Objectives', 'Value / Investment Case', 'Outcome Roadmap'], frameworks: ['OKRs', 'Balanced Scorecard'] },
      { name: 'Discovery', summary: 'Understand the current landscape, constraints and opportunity before committing capital.', deliverables: ['Current-State Assessment', 'Stakeholder Map', 'Opportunity Baseline'], frameworks: ['Design Thinking', 'Value Stream Mapping'] },
      { name: 'Planning', summary: 'Translate intent into a resourced, sequenced and fundable delivery plan.', deliverables: ['Delivery Plan', 'Resource & Budget Model', 'Milestone Roadmap'], frameworks: ['PRINCE2', 'MSP', 'Agile Release Planning'] },
      { name: 'Governance', summary: 'Establish decision rights, assurance and the cadence that de-risks delivery.', deliverables: ['Governance Model', 'Steering Committee', 'RAID Register'], frameworks: ['P3O', 'Three Lines of Defence'] },
      { name: 'Execution', summary: 'Deliver with pace and control against clear quality gates and reporting.', deliverables: ['Stage / Sprint Delivery', 'Progress Reporting', 'Quality Gates'], frameworks: ['Scrum', 'SAFe', 'Kanban'] },
      { name: 'Risk Management', summary: 'See around corners with early-warning indicators and pre-agreed responses.', deliverables: ['Risk Register', 'Mitigation Plans', 'Early-Warning KPIs'], frameworks: ['MoR', 'Monte Carlo Forecasting'] },
      { name: 'Change', summary: 'Bring the organization with you so adoption is designed, not assumed.', deliverables: ['Change Impact Assessment', 'Adoption Plan', 'Comms Strategy'], frameworks: ['ADKAR', 'Kotter 8-Step'] },
      { name: 'Deployment', summary: 'Land the change safely in production with readiness and hypercare.', deliverables: ['Cutover Plan', 'Go-Live Readiness', 'Hypercare'], frameworks: ['ITIL', 'Release Management'] },
      { name: 'Benefits Realization', summary: 'Prove the value promised and hand over a measurable operating capability.', deliverables: ['Benefits Map', 'Value Tracking', 'Post-Implementation Review'], frameworks: ['MSP Benefits', 'Value Realization Office'] },
    ],
  },
  domains: [
    {
      n: '01', name: 'Strategy', icon: 'Compass',
      desc: 'Executive vision translated into fundable, deliverable roadmaps.',
      room: {
        headline: 'From ambition to a plan that holds.',
        about: [
          'Most organisations have a strategy. Few have one that survives contact with delivery. The gap between a compelling vision and a programme that actually gets funded, resourced and executed is where most transformation efforts stall. Not because the ambition was wrong, but because the translation work was never done properly.',
          'Virellis works at the intersection of executive intent and operational reality. That means stress-testing the strategy before it becomes a plan, identifying where assumptions are optimistic, where dependencies are hidden, and where stakeholder alignment is more fragile than it looks in the presentation.',
          'The output is a roadmap with real structural integrity. One that finance can fund, the board can sponsor, delivery teams can execute against, and leadership can defend when things get hard. Not a vision document. A delivery-grade plan.',
        ],
        approach: [
          'Strategy work at Virellis starts with listening, to what leadership says the organisation needs, and to what the data and operating reality actually show. The two are often different, and that gap is where the most important work happens.',
          'We use a structured discovery process to surface the constraints, pressures and political realities that rarely appear in strategy decks. From there we build the options analysis, test the assumptions, sequence the workstreams and produce the business case in the language of the board. Financial, risk-adjusted and tied to outcomes that matter to the organisation, not just to the programme team.',
        ],
        challenges: [
          { q: 'We have a strategy but no one agrees on what it means in practice.', a: 'Virellis facilitates structured alignment to translate high-level intent into shared, specific commitments.' },
          { q: 'We need a business case that will survive scrutiny.', a: 'We build investment narratives that are financially rigorous, risk-aware and written for decision-makers.' },
          { q: 'Our roadmap keeps changing and no one trusts it.', a: 'We redesign the roadmap architecture so it is sequenced on logic, not politics.' },
          { q: 'We have three competing strategies and no way to choose.', a: 'Structured options analysis with clear evaluation criteria and a recommended path forward.' },
        ],
        deliver: [
          'Transformation roadmaps with sequencing, dependencies and milestones',
          'Business case development, strategic, financial and risk narrative',
          'Strategic options analysis and scenario modelling',
          'Operating model design aligned to strategic intent',
          'Stakeholder alignment workshops and executive facilitation',
          'Strategy-to-delivery translation and workstream design',
          'Investment prioritisation frameworks across the portfolio',
        ],
        audience: 'Boards and C-suite teams who have a direction but need a delivery-grade plan behind it. Or organisations where the strategy exists but the execution model does not.',
        quote: 'A strategy that cannot be delivered is not a strategy. It is a wish. The work is building the bridge between the two.',
      },
    },
    {
      n: '02', name: 'Governance', icon: 'ShieldCheck',
      desc: 'Assurance, controls and decision rights that de-risk delivery.',
      room: {
        headline: 'The framework that keeps large programmes honest.',
        about: [
          'Governance has a reputation for slowing things down. In practice, weak governance is what slows things down. Decisions made by the wrong people, risks that surface too late, reporting that tells leadership what they want to hear rather than what they need to act on.',
          'Good governance is a delivery accelerator. When decision rights are clear, escalation paths are trusted, and assurance processes are proportionate to the programme risk profile, delivery teams spend less time in ambiguity and more time executing. Leadership gets earlier warning of problems and faster routes to resolution.',
          'Virellis designs governance frameworks that are fit for purpose. Not copied from a methodology template and not so elaborate that the programme spends more time governing itself than delivering. The right level of control for the right level of risk, embedded in ways that the team will actually follow.',
        ],
        approach: [
          'We start with a governance diagnostic, mapping existing decision rights, reporting flows, risk escalation paths and assurance mechanisms against the programme\u2019s actual risk profile and stakeholder expectations. This surfaces the gaps quickly: where decisions are being made at the wrong level, where risks are being managed informally, where reporting is creating noise rather than signal.',
          'From there we design the governance architecture, terms of reference, RACI structures, risk frameworks, reporting cadences and gate review processes, and embed them with the team. Governance design is only half the work. The other half is making sure it gets used.',
        ],
        challenges: [
          { q: 'We have a steering committee but decisions do not get made.', a: 'We redesign terms of reference and decision authority so the right people are deciding the right things.' },
          { q: 'Our risk register is full but nothing gets escalated.', a: 'We build escalation protocols with clear thresholds and ownership so risk management is active, not administrative.' },
          { q: 'The board does not trust the programme reporting.', a: 'We redesign reporting to surface what matters. Not just status, but confidence, risk and recommended actions.' },
          { q: 'We are in a regulated environment and need audit-ready controls.', a: 'We design control frameworks proportionate to regulatory requirements, with evidence trails built in from the start.' },
        ],
        deliver: [
          'Programme governance frameworks and RACI structures',
          'Terms of reference for boards, steering committees and working groups',
          'Risk and issue management frameworks with escalation protocols',
          'Board and steering committee reporting design',
          'Gate review design and independent assurance',
          'Controls frameworks for regulated environments',
          'Governance diagnostic and reset for distressed programmes',
          'Assurance reviews, health checks, deep dives and readiness assessments',
        ],
        audience: 'Programmes operating in regulated environments, organisations that have experienced delivery failures and need to rebuild board confidence, or large programmes where governance has become a bottleneck rather than an enabler.',
        quote: 'The best governance frameworks are the ones the team stops noticing, because they just work.',
      },
    },
    {
      n: '03', name: 'AI', icon: 'Sparkles',
      desc: 'Applied intelligence embedded across the delivery lifecycle.',
      room: {
        headline: 'AI that earns its place in the delivery model.',
        about: [
          'Most enterprises are somewhere between curiosity and commitment on AI. Running pilots, exploring tools, building policies, but not yet at the point where AI is systematically changing how programmes are run. The gap between experimentation and embedded capability is where Virellis works.',
          'This is not about implementing AI for its own sake. It is about identifying where applied intelligence creates real leverage in the delivery lifecycle, faster risk identification, more accurate forecasting, automated reporting, better decision support, and building the governance, data and operating model foundations to make that capability sustainable.',
          'The result is AI that actually changes outcomes, not AI that lives in a demo environment and gets referenced in a board paper.',
        ],
        approach: [
          'Virellis takes a use-case-first approach to AI adoption. Before recommending any tooling or technology, we map the delivery lifecycle to identify where AI creates the most leverage. Typically in areas where the team is processing large volumes of information, making repeated judgement calls with incomplete data, or spending significant time on reporting and documentation that could be automated.',
          'From there we assess data readiness, governance requirements and change management needs, then sequence adoption in a way that builds confidence and capability incrementally. Enterprise AI adoption fails most often because the organisation was not ready for it, not because the technology was wrong.',
        ],
        challenges: [
          { q: 'We have run AI pilots but nothing has scaled.', a: 'We diagnose why, usually data quality, governance gaps or change management, and build a structured adoption pathway.' },
          { q: 'We do not know where AI actually adds value for us.', a: 'We run a structured opportunity mapping exercise across your delivery lifecycle to identify highest-value use cases.' },
          { q: 'Our board is asking about AI but we have no strategy.', a: 'We develop an AI adoption strategy with governance framework, use case prioritisation and investment narrative.' },
          { q: 'We are worried about risk and compliance with AI tools.', a: 'We design AI governance frameworks that address regulatory requirements, bias risk and data sovereignty.' },
        ],
        deliver: [
          'AI opportunity mapping across the delivery and programme lifecycle',
          'AI adoption strategy and implementation roadmap',
          'AI governance and responsible use frameworks',
          'Intelligent PMO tooling design and implementation oversight',
          'AI-assisted risk identification and dependency analysis',
          'Automated reporting and executive dashboard design',
          'Capability building and change management for AI adoption',
          'AI vendor assessment and procurement support',
        ],
        audience: 'Enterprises that want to move beyond AI experimentation and embed applied intelligence into how programmes are planned, governed and delivered. Particularly relevant in regulated sectors where governance and risk management are non-negotiable.',
        quote: 'The question is not whether to use AI. It is whether your organisation is ready to use it well.',
      },
    },
    {
      n: '04', name: 'Delivery', icon: 'Rocket',
      desc: 'Predictable execution of complex, multi-year programmes.',
      room: {
        headline: 'The discipline that turns plans into outcomes.',
        about: [
          'Delivery is where strategy either holds or collapses. Plans that looked coherent in a slide deck start showing their weaknesses when the first dependencies are missed, the first resources are pulled, and the first stakeholder loses confidence. Managing that reality, not just reporting on it, is what senior delivery leadership is for.',
          'Virellis leads complex, multi-year programmes from initiation through to benefits realisation. That means being in the room when hard decisions get made, maintaining momentum when the programme hits pressure, and keeping the executive picture honest even when the news is difficult.',
          'Predictable delivery is not about having a perfect plan. It is about having the discipline, the judgement and the early-warning mechanisms to keep the programme on track when the plan meets reality.',
        ],
        approach: [
          'Every programme Virellis leads starts with a structured initiation. Establishing the delivery architecture, agreeing the methodology, mapping dependencies and setting up the governance and reporting infrastructure before execution begins. The time spent here saves multiples of it downstream.',
          'During delivery, we operate as the senior accountable leader. Not just a programme manager tracking tasks, but an executive-level presence driving pace, managing stakeholders and making calls. We maintain a live delivery confidence model that gives leadership an honest view of where the programme is and what it needs to stay on track.',
        ],
        challenges: [
          { q: 'Our programme has lost momentum and we do not know why.', a: 'We conduct a rapid delivery diagnostic covering dependencies, governance, team dynamics and stakeholder confidence, then build a recovery plan.' },
          { q: 'We have a plan but no one is accountable for it.', a: 'Virellis steps in as senior delivery lead, establishing clear ownership and driving execution.' },
          { q: 'We keep delivering outputs but not outcomes.', a: 'We redesign the benefits realisation framework and connect delivery milestones to measurable business outcomes.' },
          { q: 'Our methodology is not working but we cannot agree on an alternative.', a: 'We assess the programme context and design a hybrid approach that fits the team, the work and the stakeholder environment.' },
        ],
        deliver: [
          'End-to-end programme and project leadership',
          'Delivery methodology design, agile, waterfall, hybrid and scaled frameworks',
          'Programme initiation and mobilisation',
          'Dependency and critical path management',
          'Benefits realisation planning, tracking and reporting',
          'Delivery confidence modelling and early warning systems',
          'Programme recovery and rescue for distressed delivery',
          'Senior accountable owner and SRO advisory support',
        ],
        audience: 'Organisations running complex, high-stakes programmes that need senior delivery leadership, not just coordination. Particularly relevant for multi-year transformation programmes, programmes in recovery, or organisations without internal programme leadership capability at the scale they need.',
        quote: 'Plans are not delivery. The judgement to navigate what the plan did not anticipate, that is delivery.',
      },
    },
    {
      n: '05', name: 'Data', icon: 'Database',
      desc: 'Trusted data foundations that power confident decisions.',
      room: {
        headline: 'You cannot govern what you cannot measure.',
        about: [
          'Most transformation programmes are making decisions with incomplete information. Not because the data does not exist, but because it lives in the wrong places, is owned by the wrong people, is defined inconsistently across systems, and has never been turned into something a programme leader or executive can actually use.',
          'The result is reporting that nobody fully trusts, risk assessments based on anecdote rather than evidence, and board conversations that rely on judgement where they should rely on data.',
          'Virellis builds the data foundations that change that picture. From governance frameworks that establish clear ownership and quality standards, to the reporting infrastructure that turns raw programme and operational data into the executive intelligence that drives confident decision-making.',
        ],
        approach: [
          'Data work at Virellis starts with a data landscape assessment, mapping what data exists, where it lives, how it is defined, who owns it and how it currently flows into programme and executive reporting. This typically surfaces more complexity than the organisation expected and more opportunity than it realised.',
          'From there we design the governance layer, data ownership, quality standards, lineage and stewardship, before moving to the reporting infrastructure and dashboard design. The sequence matters. Reporting built on ungoverned data just automates the problem. We fix the foundation first.',
        ],
        challenges: [
          { q: 'Our programme dashboard shows different numbers every week.', a: 'We establish a single source of truth with clear data ownership and a governed reporting pipeline.' },
          { q: 'We have data everywhere but no one trusts any of it.', a: 'We run a data quality assessment and build a remediation plan with accountable owners.' },
          { q: 'The board keeps asking for data we cannot produce quickly.', a: 'We design the reporting infrastructure and data architecture to make executive reporting systematic, not manual.' },
          { q: 'We are merging systems and do not know how to handle the data.', a: 'We design the master data management strategy and migration governance framework.' },
        ],
        deliver: [
          'Data landscape assessment and gap analysis',
          'Data governance frameworks covering ownership, stewardship and quality standards',
          'Master data management strategy and implementation oversight',
          'Programme reporting infrastructure and data pipeline design',
          'Executive dashboard design and single source of truth architecture',
          'Data quality assessment and remediation planning',
          'Data strategy aligned to transformation objectives',
          'Regulatory data compliance and audit-readiness',
        ],
        audience: 'Organisations where fragmented or untrustworthy data is creating blind spots in programme management or executive decision-making. Particularly those undergoing system consolidation, regulatory scrutiny, or large-scale operational transformation.',
        quote: 'Data governance is not an IT problem. It is a leadership problem. We solve it at both levels.',
      },
    },
    {
      n: '06', name: 'Cloud', icon: 'Cloud',
      desc: 'Modern platforms engineered for scale and resilience.',
      room: {
        headline: 'Platform decisions the programme can build on.',
        about: [
          'Cloud migration and modernisation programmes fail most often not because of the technology, but because of unclear ownership, underestimated complexity, and governance structures that cannot keep pace with the technical work. The gap between what the architecture team is building and what the executive team believes is being built is where programmes get into trouble.',
          'Virellis brings programme leadership and strategic oversight to cloud transformation. Ensuring that platform decisions are made with the full delivery context in view, that risks are identified before they become incidents, and that the migration is sequenced in a way that the business can absorb.',
          'This is not a technical delivery service. It is the strategic and programme layer that bridges the gap between engineering teams and the executive stakeholders who need to understand what is being built, why, and what it will cost if something goes wrong.',
        ],
        approach: [
          'Cloud programme oversight at Virellis begins with a strategy and readiness assessment. Understanding the current estate, the target architecture, the business drivers and the constraints that will shape how the migration can realistically be sequenced. This surfaces the gaps in planning that are most likely to cause problems: underestimated dependencies, inadequate cutover planning, governance structures that are too slow for the pace of cloud delivery.',
          'From there we design the programme governance and reporting infrastructure, establish the risk management framework, and work alongside the technical teams to maintain executive visibility and delivery confidence throughout the migration.',
        ],
        challenges: [
          { q: 'Our cloud migration is running late and over budget.', a: 'We conduct a rapid programme assessment, identify the root causes and build a recovery plan with honest timelines.' },
          { q: 'The board does not understand what we are building or why.', a: 'We translate technical architecture into executive narrative covering investment, risk, value and timeline.' },
          { q: 'We cannot agree on which cloud provider to use.', a: 'We run a structured hyperscaler assessment against your specific workload, regulatory and commercial requirements.' },
          { q: 'We are worried about security and compliance in the cloud.', a: 'We design the cloud governance and compliance framework, including FinOps controls and regulatory alignment.' },
        ],
        deliver: [
          'Cloud strategy development and business case',
          'Migration sequencing and dependency mapping',
          'Programme governance for cloud transformation',
          'Hyperscaler and vendor assessment',
          'Cloud governance and FinOps framework design',
          'Technical to executive reporting translation',
          'Risk and compliance framework for cloud environments',
          'Cloud programme recovery and reset',
        ],
        audience: 'Enterprises mid-way through a cloud programme that has lost momentum or executive confidence. Or organisations planning a major platform migration who want senior programme oversight from the start, not just when things go wrong.',
        quote: 'The cloud decision is rarely the hard part. Governing the programme that executes it, that is where the work is.',
      },
    },
    {
      n: '07', name: 'PMO', icon: 'LayoutDashboard',
      desc: 'Next-generation portfolio and programme operating models.',
      room: {
        headline: 'A PMO that runs the enterprise, not just the spreadsheet.',
        about: [
          'The PMO has a reputation problem, and often a function problem. Too many portfolio offices are built around status reporting and RAG updates rather than decision support and delivery acceleration. They produce information but do not change outcomes. They govern the paperwork but not the programme.',
          'The result is that leadership teams stop trusting the PMO, delivery teams treat it as an overhead, and the function spends its energy justifying its existence rather than adding value.',
          'Virellis designs PMO operating models that actually change delivery outcomes. Giving leadership the real-time visibility they need, the governance frameworks delivery teams will follow, and the portfolio intelligence to make better investment and prioritisation decisions. Whether you are building a PMO from scratch, resetting one that has lost credibility, or scaling an existing function to match portfolio growth, Virellis brings both the architecture and the operating discipline.',
        ],
        approach: [
          'PMO design at Virellis starts with a maturity and fit assessment, understanding what the organisation needs from its portfolio function, what the current PMO is and is not delivering, and where the gaps are most damaging. This is as much an organisational and cultural assessment as a process one. PMO functions fail for people reasons as often as process ones.',
          'From there we design the operating model, the services the PMO provides, the processes it runs, the tools it uses, the reporting it produces and the governance it supports, and implement it with the team. We do not hand over a framework and leave. We embed the capability.',
        ],
        challenges: [
          { q: 'Our PMO produces reports but does not influence decisions.', a: 'We redesign the PMO service model so it produces decision-relevant intelligence, not just status updates.' },
          { q: 'We have 40 projects running and no idea which ones matter.', a: 'We build a portfolio prioritisation framework with clear criteria, investment logic and dependency mapping.' },
          { q: 'Delivery teams see the PMO as a bureaucratic overhead.', a: 'We reset the PMO operating model to be delivery-enabling rather than delivery-policing.' },
          { q: 'We need to stand up a PMO from scratch in three months.', a: 'We design and implement a right-sized PMO operating model built for your portfolio scale and complexity.' },
        ],
        deliver: [
          'PMO operating model design and implementation',
          'Portfolio management frameworks and prioritisation models',
          'Resource and capacity planning infrastructure',
          'Programme reporting design and executive dashboard development',
          'Benefits tracking and portfolio performance management',
          'PMO maturity assessment and capability reset',
          'Tooling selection and implementation oversight',
          'PMO-as-a-service for organisations without internal capability',
        ],
        audience: 'Organisations whose PMO has become a reporting function rather than a delivery enabler. Or those building portfolio management capability for the first time and wanting to get the model right from the start.',
        quote: 'A PMO that is feared is broken. A PMO that is ignored is useless. The goal is one that is trusted.',
      },
    },
    {
      n: '08', name: 'Innovation', icon: 'Lightbulb',
      desc: 'New operating models that compound enterprise value.',
      room: {
        headline: 'The thinking that stays useful after the engagement ends.',
        about: [
          'Innovation in the context of enterprise transformation is not about ideation sessions and innovation labs. It is about building operating models, ways of working and organisational capability that allow the enterprise to keep evolving, to absorb change, to adopt new technology, and to deliver at pace, after the programme closes and the consultant has left.',
          'Most transformation programmes deliver the thing they were commissioned to deliver. The better question is whether the organisation is structurally different, more capable, more adaptive, more confident in its ability to execute, when the work is done. That is the measure of transformation that actually compounds.',
          'Virellis works with leadership teams to identify where new operating models can unlock that kind of structural value, and to build the capability to sustain it.',
        ],
        approach: [
          'Innovation work at Virellis begins with a capability and operating model assessment, understanding how the organisation currently makes decisions, adopts new ways of working, and absorbs change. This typically reveals specific structural constraints: governance models that are too slow, capability gaps in the leadership layer, incentive structures that reward the wrong behaviours, or change management approaches that produce compliance rather than genuine adoption.',
          'From there we design the interventions, new operating models, capability programmes, ways of working, governance structures, that address the root causes rather than the symptoms. And we build them in ways that the organisation can own and sustain without ongoing external support.',
        ],
        challenges: [
          { q: 'We keep delivering programmes but the organisation does not seem to change.', a: 'We diagnose the structural barriers to change absorption and design operating model interventions that address them.' },
          { q: 'We want to build internal transformation capability but do not know where to start.', a: 'We design a capability development programme tailored to your organisation context and delivery ambition.' },
          { q: 'Our ways of working are slowing us down but we cannot agree on alternatives.', a: 'We facilitate the design of new ways of working with the team, building ownership rather than imposing a framework.' },
          { q: 'We need to do more with less, automation and efficiency are the priority.', a: 'We map the highest-value automation opportunities and build the operating model to capture them systematically.' },
        ],
        deliver: [
          'Operating model design and transformation',
          'Organisational capability assessment and development planning',
          'New ways of working design and implementation',
          'Intelligent automation opportunity mapping and roadmap',
          'Change management strategy and leadership alignment',
          'Innovation governance and portfolio management',
          'Internal transformation capability building',
          'Post-programme sustainability and embedment planning',
        ],
        audience: 'Leadership teams who want transformation to leave the organisation structurally better, more capable, more adaptive and more confident in its ability to deliver, not just to have completed a project on time and on budget.',
        quote: 'The best transformation is the one that makes the next one easier. That is what structural change looks like.',
      },
    },
  ],
  metrics: {
    eyebrow: 'WHAT WE BRING TO THE TABLE',
    title: 'Outcomes leadership teams can put in front of the board.',
    items: [
      { value: 8, suffix: '+', decimals: 0, label: 'Years in senior delivery' },
      { value: 6, suffix: '', decimals: 0, label: 'Regulated industries served' },
      { display: 'C-suite', label: 'Stakeholder advisory' },
      { display: 'Global', label: 'Multi-region programmes' },
    ],
  },
  founder: {
    eyebrow: 'THE PRINCIPAL',
    role: 'Founder & Principal Consultant',
    name: 'Fidelis Chick',
    bio: [
      'Fidelis Chick has spent eight years in the room where transformation decisions get made, and where they fall apart. Working across government, financial services, and enterprise technology, he has led programmes where failure was not an option and built the governance frameworks to prove it.',
      'Virellis exists because most enterprises have the strategy. What they lack is the operating model to deliver it. That gap is where he works.',
    ],
    quote: 'Complexity is not the enemy. Unmanaged complexity is what derails programmes. My work is turning ambiguity into a delivery model the board can trust.',
    image: '/founder.jpg',
    stats: [
      { k: '8+', v: 'Years leading delivery' },
      { k: 'C-suite', v: 'Advisory & assurance' },
      { k: 'Global', v: 'Multi-region programmes' },
    ],
  },
  leadership: {
    eyebrow: 'LEADERSHIP PHILOSOPHY',
    title: 'How Virellis leads when the programme gets hard.',
    subtitle: 'Delivery is a leadership discipline before it is a technical one. These are the principles that hold when the plan meets reality. Select a node to explore each one.',
    nodes: [
      { name: 'Strategy', x: 18, y: 16, principle: 'Lead from the outcome, not the activity.', story: 'Every decision is tested against the outcome the board signed up for. When priorities compete, the strategy is the tiebreaker, not the loudest voice in the room.' },
      { name: 'Governance', x: 50, y: 9, principle: 'Make the right decision easy to make.', story: 'Good governance removes ambiguity about who decides what, and when. It is designed to accelerate delivery, not to create a paper trail nobody reads.' },
      { name: 'Delivery', x: 82, y: 18, principle: 'Momentum is a leadership responsibility.', story: 'Programmes rarely fail in one dramatic moment. They stall quietly. The job is to protect pace and surface friction early, before it compounds.' },
      { name: 'Trust', x: 12, y: 44, principle: 'Credibility is earned in the difficult updates.', story: 'Anyone can report green. Trust is built by naming the hard truth early, with a plan attached, so leadership is never surprised.' },
      { name: 'Execution', x: 44, y: 40, principle: 'Judgement is the work the plan cannot do.', story: 'Plans set the direction. Execution is the thousand judgement calls the plan never anticipated, made under pressure with incomplete information.' },
      { name: 'Stakeholders', x: 68, y: 44, principle: 'Alignment is engineered, not assumed.', story: 'Stakeholders rarely disagree on the goal. They disagree on the trade-offs. The work is making those trade-offs explicit and shared.' },
      { name: 'Communication', x: 80, y: 66, principle: 'Clarity is a form of respect.', story: 'Executives do not need more information. They need the signal: where we are, what is at risk, and the decision required of them.' },
      { name: 'Transparency', x: 26, y: 78, principle: 'No surprises, ever.', story: 'Bad news does not improve with age. Surfacing it early, honestly and with options is what keeps a programme governable.' },
      { name: 'Continuous Improvement', x: 56, y: 80, principle: 'Leave the organisation more capable.', story: 'The measure of a great engagement is whether the next one is easier. Every programme should build capability that outlasts the consultant.' },
    ],
    edges: [[0, 1], [1, 2], [0, 3], [1, 4], [2, 5], [3, 4], [4, 5], [5, 6], [3, 7], [4, 8], [7, 8], [8, 5], [6, 2]],
  },
  testimonials: {
    eyebrow: 'VOICES FROM THE BOARDROOM',
    title: 'Trusted where the stakes are highest.',
    subtitle: 'Recommendations from the sponsors, executives and boards Virellis has delivered alongside. Illustrative, pending publication of named references.',
    items: [
      { quote: 'Fidelis brought order to a programme the board had almost written off. Within a quarter we had governance we trusted and a delivery plan we could defend.', name: 'Helena Marsh', role: 'Managing Director', org: 'Financial Services' },
      { quote: 'The clarity he brought to our reporting changed how the executive committee made decisions. For the first time we were looking at the real picture.', name: 'David Okoro', role: 'Chief Operating Officer', org: 'Healthcare' },
      { quote: 'Most consultants hand you a framework and leave. Virellis embedded a capability our team still runs today, long after the engagement closed.', name: 'Sarah Lindqvist', role: 'Portfolio Director', org: 'Government' },
      { quote: 'He was in the room for the hardest decisions and made the calls that kept the programme alive when it mattered most.', name: 'Marcus Reid', role: 'Senior Responsible Owner', org: 'Enterprise Technology' },
      { quote: 'Our AI ambitions were stuck in pilots. He built the adoption model that finally scaled them responsibly, with the governance to back it.', name: 'Priya Nair', role: 'Chief Data Officer', org: 'Telecommunications' },
      { quote: 'The governance he designed was proportionate, trusted and, remarkably, something the team actually used rather than resented.', name: 'Thomas Byrne', role: 'Steering Committee Chair', org: 'Retail' },
    ],
  },
  governance: {
    eyebrow: 'THE GOVERNANCE ROOM',
    title: 'The artifacts that keep programmes governable.',
    subtitle: 'The operating instruments Virellis stands up on every engagement. Open any artifact to see how governance is made tangible.',
    artifacts: [
      {
        title: 'Project Charter', icon: 'FileText', tag: 'CHARTER',
        summary: 'Establishes the mandate, scope and authority for the programme.',
        fields: [
          { k: 'Programme', v: 'Enterprise Delivery Modernisation' },
          { k: 'Sponsor', v: 'Chief Operating Officer' },
          { k: 'Objective', v: 'Governed, predictable delivery across the portfolio' },
          { k: 'Scope', v: 'Strategy, governance, PMO, AI enablement' },
          { k: 'Authority', v: 'SRO with steering committee oversight' },
        ],
      },
      {
        title: 'Business Case', icon: 'Landmark', tag: 'BUSINESS CASE',
        summary: 'The financial and strategic justification the board signs.',
        fields: [
          { k: 'Strategic fit', v: 'High' },
          { k: 'Preferred option', v: 'Phased transformation' },
          { k: 'Payback', v: 'Within programme horizon' },
          { k: 'Risk profile', v: 'Managed, risk-adjusted' },
        ],
        list: [
          'Do nothing: rejected, delivery risk rising',
          'Minimal change: partial, root cause unresolved',
          'Recommended: phased operating-model transformation',
        ],
      },
      {
        title: 'RAID Register', icon: 'ClipboardList', tag: 'RAID',
        summary: 'Risks, assumptions, issues and dependencies, actively managed.',
        table: {
          cols: ['Type', 'Item', 'Owner', 'Status'],
          rows: [
            ['Risk', 'Vendor on the critical path', 'Delivery Lead', 'Amber'],
            ['Assumption', 'Phase 2 funding confirmed', 'Sponsor', 'Open'],
            ['Issue', 'Reporting inconsistent across teams', 'PMO', 'In progress'],
            ['Dependency', 'Data migration precedes go-live', 'Data Lead', 'Tracked'],
          ],
        },
      },
      {
        title: 'Risk Register', icon: 'ShieldAlert', tag: 'RISK',
        summary: 'Prioritised risks with mitigations and clear ownership.',
        table: {
          cols: ['Risk', 'Likelihood', 'Impact', 'Mitigation'],
          rows: [
            ['Scope creep in phase 2', 'Medium', 'High', 'Change control and gate reviews'],
            ['Key resource attrition', 'Low', 'High', 'Succession and knowledge capture'],
            ['Integration complexity', 'Medium', 'Medium', 'Early proofs of concept'],
            ['Regulatory change', 'Low', 'High', 'Compliance watch and buffer'],
          ],
        },
      },
      {
        title: 'Roadmap', icon: 'Map', tag: 'ROADMAP',
        summary: 'The sequenced path from mobilisation to benefits.',
        table: {
          cols: ['Phase', 'Focus', 'Horizon'],
          rows: [
            ['Mobilise', 'Governance, baseline, plan', 'Q1'],
            ['Foundation', 'Data, PMO, controls', 'Q2'],
            ['Deliver', 'Execution at pace', 'Q3 to Q4'],
            ['Realise', 'Benefits, embed capability', 'Q4 and beyond'],
          ],
        },
      },
      {
        title: 'Steering Committee Deck', icon: 'Presentation', tag: 'STEERCO',
        summary: 'The monthly executive decision pack.',
        list: [
          'Delivery confidence and portfolio health',
          'Key risks and escalations',
          'Decisions required this cycle',
          'Budget and benefits tracking',
          'Next-period priorities',
        ],
      },
      {
        title: 'Communication Plan', icon: 'Megaphone', tag: 'COMMS',
        summary: 'Who hears what, how, and how often.',
        table: {
          cols: ['Audience', 'Channel', 'Frequency'],
          rows: [
            ['Board', 'Executive summary', 'Monthly'],
            ['Steering committee', 'Decision pack', 'Monthly'],
            ['Delivery teams', 'Stand-up and report', 'Weekly'],
            ['Wider organisation', 'Change comms', 'Milestone'],
          ],
        },
      },
      {
        title: 'Decision Register', icon: 'Gavel', tag: 'DECISIONS',
        summary: 'A durable record of what was decided, by whom.',
        table: {
          cols: ['Decision', 'Owner', 'Status'],
          rows: [
            ['Adopt hybrid delivery methodology', 'SRO', 'Approved'],
            ['Consolidate reporting to one source', 'PMO', 'Approved'],
            ['Prioritise AI use cases for phase 2', 'CDO', 'Pending'],
            ['Confirm phase 2 funding', 'Sponsor', 'In review'],
          ],
        },
      },
    ],
  },
  command: {
    eyebrow: 'THE COMMAND CENTER',
    title: 'Step inside the enterprise transformation command center.',
    subtitle: 'A conversational AI concierge, live portfolio telemetry and a governance operating model.',
    cta: 'Book a Strategy Session',
    modules: ['AI Concierge', 'Live PMO Dashboard', 'Governance Room', 'Delivery Framework'],
  },
  industries: ['Government', 'Healthcare', 'Financial Services', 'Technology', 'Retail', 'Telecommunications', 'Consulting'],
  footer: {
    tagline: 'Strategy is easy. Delivery is the work. Virellis does the work.',
    columns: [
      { title: 'Studio', links: ['Strategy', 'Governance', 'Delivery', 'AI Adoption'] },
      { title: 'Firm', links: ['Founder', 'Approach', 'Insights', 'Contact'] },
      { title: 'Command Center', links: ['AI Concierge', 'PMO Dashboard', 'Frameworks', 'Playbooks'] },
    ],
  },
}
